{{- if and .Values.master.enabled .Values.master.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "blob-storage.fullname" . }}-master
  labels:
    {{- include "blob-storage.master.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.master.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.master.persistence.size }}
  {{- if or .Values.master.persistence.storageClass .Values.global.storageClass }}
  storageClassName: {{ .Values.master.persistence.storageClass | default .Values.global.storageClass }}
  {{- end }}
{{- end }}
