{{- if .Values.master.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blob-storage.master.serviceName" . }}
  labels:
    {{- include "blob-storage.master.labels" . | nindent 4 }}
  {{- with .Values.master.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.master.service.type }}
  ports:
  - port: {{ .Values.master.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "blob-storage.master.selectorLabels" . | nindent 4 }}
{{- end }}
