{{- if .Values.database.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freshrss.fullname" . }}-db
type: Opaque
data:
  username: {{ .Values.database.secret.username | b64enc | quote }}
  password: {{ .Values.database.secret.password | b64enc | quote }}
{{- end }}
