apiVersion: v2
name: blob-storage
description: A distributed filesystem with master, chunkservers, client API, and web frontend
type: application
version: 0.1.3
appVersion: "0.1.0"
keywords:
  - blob-storage
maintainers:
  - name: Bartlomiej Klimczak
